# RealEstatePRO

In [2]:
#import all necessary libraries
import pandas as pd
import os
from getpass import getpass
from langchain_openai import OpenAIEmbeddings
import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
import tqdm

In [3]:
os.environ["LANGCHAIN_API_KEY"] = os.getenv("LANGCHAIN_API_KEY") or \
    getpass("Enter LangSmith API Key: ")

os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGCHAIN_PROJECT"] = "aurelioai-langchain-course-agent-executor-openai"

In [4]:
os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY") \
    or getpass("Enter your OpenAI API key: ")

## DataFrame import

In [5]:
df = pd.read_csv('NY-House-Dataset.csv')

In [6]:
df.head(10)

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo for sale,315000,2,2.000000,1400.000000,2 E 55th St Unit 803,"New York, NY 10022","2 E 55th St Unit 803New York, NY 10022",New York County,New York,Manhattan,East 55th Street,Regis Residence,"Regis Residence, 2 E 55th St #803, New York, N...",40.761255,-73.974483
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.000000,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991
2,Brokered by Sowae Corp,House for sale,260000,4,2.000000,2015.000000,620 Sinclair Ave,"Staten Island, NY 10312","620 Sinclair AveStaten Island, NY 10312",United States,New York,Richmond County,Staten Island,Sinclair Avenue,"620 Sinclair Ave, Staten Island, NY 10312, USA",40.541805,-74.196109
3,Brokered by COMPASS,Condo for sale,69000,3,1.000000,445.000000,2 E 55th St Unit 908W33,"Manhattan, NY 10022","2 E 55th St Unit 908W33Manhattan, NY 10022",United States,New York,New York County,New York,East 55th Street,"2 E 55th St, New York, NY 10022, USA",40.761398,-73.974613
4,Brokered by Sotheby's International Realty - E...,Townhouse for sale,55000000,7,2.373861,14175.000000,5 E 64th St,"New York, NY 10065","5 E 64th StNew York, NY 10065",United States,New York,New York County,New York,East 64th Street,"5 E 64th St, New York, NY 10065, USA",40.767224,-73.969856
5,Brokered by Sowae Corp,House for sale,690000,5,2.000000,4004.000000,584 Park Pl,"Brooklyn, NY 11238","584 Park PlBrooklyn, NY 11238",United States,New York,Kings County,Brooklyn,Park Place,"584 Park Pl, Brooklyn, NY 11238, USA",40.674363,-73.958725
6,Brokered by Douglas Elliman - 575 Madison Ave,Condo for sale,899500,2,2.000000,2184.207862,157 W 126th St Unit 1B,"New York, NY 10027","157 W 126th St Unit 1BNew York, NY 10027",New York,New York County,New York,Manhattan,157,"157 W 126th St #1b, New York, NY 10027, USA",40.809448,-73.946777
7,Brokered by Connie Profaci Realty,House for sale,16800000,8,16.000000,33000.000000,177 Benedict Rd,"Staten Island, NY 10304","177 Benedict RdStaten Island, NY 10304",United States,New York,Richmond County,Staten Island,Benedict Road,"177 Benedict Rd, Staten Island, NY 10304, USA",40.595002,-74.106424
8,Brokered by Pantiga Group Inc.,Co-op for sale,265000,1,1.000000,750.000000,875 Morrison Ave Apt 3M,"Bronx, NY 10473","875 Morrison Ave Apt 3MBronx, NY 10473",Bronx County,The Bronx,East Bronx,Morrison Avenue,Parking lot,"Parking lot, 875 Morrison Ave #3m, Bronx, NY 1...",40.821586,-73.874089
9,Brokered by CENTURY 21 MK Realty,Co-op for sale,440000,2,1.000000,978.000000,1350 Ocean Pkwy Apt 5G,"Brooklyn, NY 11230","1350 Ocean Pkwy Apt 5GBrooklyn, NY 11230",New York,Kings County,Brooklyn,Midwood,1350,"1350 Ocean Pkwy #5g, Brooklyn, NY 11230, USA",40.615738,-73.969694

In [7]:
df.describe()

,PRICE,BEDS,BATH,PROPERTYSQFT,LATITUDE,LONGITUDE
count,4.801000e+03,4801.000000,4801.000000,4801.000000,4801.000000,4801.000000
mean,2.356940e+06,3.356801,2.373861,2184.207862,40.714227,-73.941601
std,3.135525e+07,2.602315,1.946962,2377.140894,0.087676,0.101082
min,2.494000e+03,1.000000,0.000000,230.000000,40.499546,-74.253033
25%,4.990000e+05,2.000000,1.000000,1200.000000,40.639375,-73.987143
50%,8.250000e+05,3.000000,2.000000,2184.207862,40.726749,-73.949189
75%,1.495000e+06,4.000000,3.000000,2184.207862,40.771923,-73.870638
max,2.147484e+09,50.000000,50.000000,65535.000000,40.912729,-73.702450

In [8]:
df.shape

(4801, 17)

In [9]:
#make all columns lowercase
df.columns = [col.lower() for col in df.columns]

In [10]:
df.columns

Index(['brokertitle', 'type', 'price', 'beds', 'bath', 'propertysqft',
       'address', 'state', 'main_address', 'administrative_area_level_2',
       'locality', 'sublocality', 'street_name', 'long_name',
       'formatted_address', 'latitude', 'longitude'],
      dtype='object')

### Save embeddings in FAISS

What is FAISS: TODO

In [12]:
index_path = "faiss_index_dir"
embeddings = OpenAIEmbeddings(model="text-embedding-3-large")

In [14]:
if os.path.exists(index_path):
    # Load existing FAISS index
    vector_store = FAISS.load_local(index_path, embeddings, allow_dangerous_deserialization=True)
    print("Loaded existing FAISS index.")

Loaded existing FAISS index.

In [181]:
# Create a concise textual representation for embedding
df['text_to_embed'] = (
    df['brokertitle'].astype(str) + ", " +
    df['type'].astype(str) + ", Price: " + df['price'].astype(str) + "$, " +
    "Beds: " + df['beds'].astype(str) + ", Baths: " + df['bath'].astype(str) + ", " +
    "Size: " + df['propertysqft'].astype(str) + " sqft, " +
    "Address: " + df['address'].astype(str) + ", " +
    "Locality: " + df['locality'].astype(str) + ", " +
    "State: " + df['state'].astype(str) + ", " +
    "Latitude: " + df['latitude'].astype(str) + ", Longitude: " + df['longitude'].astype(str)
)

In [182]:
df

,brokertitle,type,price,beds,bath,propertysqft,address,state,main_address,administrative_area_level_2,locality,sublocality,street_name,long_name,formatted_address,latitude,longitude,text_to_embed
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo for sale,315000,2,2.000000,1400.000000,2 E 55th St Unit 803,"New York, NY 10022","2 E 55th St Unit 803New York, NY 10022",New York County,New York,Manhattan,East 55th Street,Regis Residence,"Regis Residence, 2 E 55th St #803, New York, N...",40.761255,-73.974483,"Brokered by Douglas Elliman -111 Fifth Ave, C..."
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.000000,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991,"Brokered by Serhant, Condo for sale, Price: 19..."
2,Brokered by Sowae Corp,House for sale,260000,4,2.000000,2015.000000,620 Sinclair Ave,"Staten Island, NY 10312","620 Sinclair AveStaten Island, NY 10312",United States,New York,Richmond County,Staten Island,Sinclair Avenue,"620 Sinclair Ave, Staten Island, NY 10312, USA",40.541805,-74.196109,"Brokered by Sowae Corp, House for sale, Price:..."
3,Brokered by COMPASS,Condo for sale,69000,3,1.000000,445.000000,2 E 55th St Unit 908W33,"Manhattan, NY 10022","2 E 55th St Unit 908W33Manhattan, NY 10022",United States,New York,New York County,New York,East 55th Street,"2 E 55th St, New York, NY 10022, USA",40.761398,-73.974613,"Brokered by COMPASS, Condo for sale, Price: 69..."
4,Brokered by Sotheby's International Realty - E...,Townhouse for sale,55000000,7,2.373861,14175.000000,5 E 64th St,"New York, NY 10065","5 E 64th StNew York, NY 10065",United States,New York,New York County,New York,East 64th Street,"5 E 64th St, New York, NY 10065, USA",40.767224,-73.969856,Brokered by Sotheby's International Realty - E...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,Brokered by COMPASS,Co-op for sale,599000,1,1.000000,2184.207862,222 E 80th St Apt 3A,"Manhattan, NY 10075","222 E 80th St Apt 3AManhattan, NY 10075",New York,New York County,New York,Manhattan,222,"222 E 80th St #3a, New York, NY 10075, USA",40.774350,-73.955879,"Brokered by COMPASS, Co-op for sale, Price: 59..."
4797,Brokered by Mjr Real Estate Llc,Co-op for sale,245000,1,1.000000,2184.207862,97-40 62 Dr Unit Lg,"Rego Park, NY 11374","97-40 62 Dr Unit LgRego Park, NY 11374",United States,New York,Queens County,Queens,62nd Drive,"97-40 62nd Dr, Rego Park, NY 11374, USA",40.732538,-73.860152,"Brokered by Mjr Real Estate Llc, Co-op for sal..."
4798,Brokered by Douglas Elliman - 575 Madison Ave,Co-op for sale,1275000,1,1.000000,2184.207862,427 W 21st St Unit Garden,"New York, NY 10011","427 W 21st St Unit GardenNew York, NY 10011",United States,New York,New York County,New York,West 21st Street,"427 W 21st St, New York, NY 10011, USA",40.745882,-74.003398,"Brokered by Douglas Elliman - 575 Madison Ave,..."
4799,Brokered by E Realty International Corp,Condo for sale,598125,2,1.000000,655.000000,91-23 Corona Ave Unit 4G,"Elmhurst, NY 11373","91-23 Corona Ave Unit 4GElmhurst, NY 11373",New York,Queens County,Queens,Flushing,91-23,"91-23 Corona Ave. #4b, Flushing, NY 11373, USA",40.742770,-73.872752,"Brokered by E Realty International Corp, Condo..."
4800,Brokered by Nyc Realty Brokers Llc,Co-op for sale,349000,1,1.000000,750.000000,460 Neptune Ave Apt 14O,"Brooklyn, NY 11224","460 Neptune Ave Apt 14OBrooklyn, NY 11224",New York,Kings County,Brooklyn,Coney Island,460,"460 Neptune Ave #14a, Brooklyn, NY 11224, USA",40.579147,-73.970949,"Brokered by Nyc Realty Brokers Llc, Co-op for ..."

In [183]:
# Create LangChain Documents, saving only essential metadata
documents = []
for idx, row in df.iterrows():
    metadata = {
        "beds": row['beds'],
        "bath": row['bath'],
        "address": row['address'],
        "state": row['state'],
        "propertysqft": row['propertysqft'],
        "price": row['price'],
        "latitude": row['latitude'],
        "longitude": row['longitude']
    }
    doc = Document(page_content=row['text_to_embed'], metadata=metadata)
    documents.append(doc)

In [184]:
documents[0]  # Display the first document to verify

Document(metadata={'beds': 2, 'bath': 2.0, 'address': '2 E 55th St Unit 803', 'state': 'New York, NY 10022', 'propertysqft': 1400.0, 'price': 315000, 'latitude': 40.761255, 'longitude': -73.9744834}, page_content='Brokered by Douglas Elliman  -111 Fifth Ave, Condo for sale, Price: 315000$, Beds: 2, Baths: 2.0, Size: 1400.0 sqft, Address: 2 E 55th St Unit 803, Locality: New York, State: New York, NY 10022, Latitude: 40.761255, Longitude: -73.9744834')

In [185]:
embedding_dim = len(embeddings.embed_query("hello world"))
index = faiss.IndexFlatL2(embedding_dim)

vector_store = FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)

In [186]:
# Add documents to the vector store 
vector_store.add_documents(documents)

['4f8a1348-0a51-461c-938d-cdd294c93ba8',
 '97c98ea5-9fe0-42b5-a40f-06d174dd0c77',
 '20a92d63-ee3e-4c0f-a943-eccd0ab62fea',
 '1d4fc045-3927-4134-b728-2e5923ac9389',
 '5898e398-80bf-48fc-9bcd-0933a732a903',
 '5a5aceaa-c0e9-45f1-9daa-ebbf365881ec',
 'de9eb690-c719-4abc-9624-d9c8f38765b7',
 '80ca480f-4cc5-46cc-8f33-13283c2d2312',
 '2c4f9783-a66c-4d7b-965c-34f2143d6a47',
 '5f99f009-f192-444c-8207-2c2c63f1e4ba',
 '6bcac79a-8994-4470-b0c2-d37a2d6009b7',
 '8d46b104-f44e-4197-8869-171055c82d48',
 '920b637e-da17-440d-8057-ae9117a56db3',
 'afdfb219-3b41-4be4-a418-f4d4b892adb2',
 'd073664a-463c-4bbb-a20c-9e25f0621688',
 'fea6a6b2-99da-4f74-9307-e2dba6a67fcb',
 '71945696-b666-44c4-9298-acf5083e38dd',
 '6eee917e-e1ae-4375-a92f-c816cb1c4b71',
 '1de8ff6c-a2cd-4f86-b55c-0a459a205ddb',
 'ea17304a-ff9a-4287-8bce-43b3a2127a46',
 '867a9f69-69f0-4695-8775-09c072e24acc',
 '8be9972a-4934-4911-9bda-6c301d0b7cec',
 '29cdcc7a-cc75-48d6-b7cc-ad1b8f9b1f3e',
 '9d391a41-7c99-40ea-88bb-0034a64a9ff6',
 '843f1b9f-2520-49ce-9956-4db05fad5ce4',
 '50bc424e-e259-4bfb-98c0-0f1a0ca7d48f',
 'cc3cff97-8e4c-4399-bc46-c937fe8ba505',
 '61ea0f26-fc5c-487c-bece-f10ba5b60420',
 '8d3c3d1d-6d44-49cd-813c-f0cb77d30af1',
 '3281a555-d918-48b3-a8ad-9db181e0cba6',
 '8a23fe91-0f33-4ffe-b101-f6c43d6bdae0',
 'bbe6d023-cff3-4500-b363-3803c37b3fc2',
 '9ff049d1-4f30-483d-ac38-d1b56f49d5f0',
 '46d6ac18-1d3e-4247-adb0-8013b50eb63b',
 '626e4784-31dd-4077-8bc4-59ab10fe3e6b',
 '9e629a1d-3f95-432d-a4a6-c97c8b8035fc',
 '51d9f72b-d160-4361-be31-0c19f2a53f87',
 'e0933534-db27-4670-b8c7-79eb5216ec75',
 '7926717e-5731-4bc2-9054-0812a6c2c26a',
 '21ca9471-ff4d-4644-b1d2-761f7dbc0d54',
 '4ef6b95c-c893-42e0-bd8a-94f49e4a49bc',
 'f8e886e2-c950-4d19-b389-19b621bc2820',
 'ab4873b9-624d-46b9-8fb6-ae0b97db8282',
 '68bd9b2d-170a-4c14-8b02-b1e31de5d0f3',
 'abaf578d-5ba7-4c58-9b18-05282b67af28',
 '53dface5-0902-4d14-a691-316af64dd9df',
 '24c4028b-b182-4be4-8954-b571d500fcd5',
 '20e2bf95-30ca-4927-a890-f2886ce2d22b',
 '91c6d17b-58e9-422f-95cb-d91efe431303',
 'd0e2d7ce-fabd-43e6-81c7-9adc6ad99d55',
 '87983825-06f4-4a8a-a0e2-a5a0616d876d',
 '0d765911-427a-4144-89b7-a0a7f14e5cfc',
 '3d92f3f8-2979-4892-b4c4-e70467e3bf58',
 '67876ab3-bcb2-419f-887f-de12b59a43bd',
 'd5cacfa2-7849-4016-bb73-61774065be80',
 'a6b36e51-b021-492b-b773-7971d292fb5c',
 '8c8fb93d-4a90-4634-aa6e-95d4d6cfbfca',
 '3927eec5-cc4c-4e81-9554-6b79f6b8f5f1',
 '8c750e72-a360-42f5-8030-345a59fb90e4',
 '9755926d-e39d-40a8-b02d-1d29a5f4c506',
 'c8cf5cdc-c815-498d-8a7b-d27af24de259',
 '86292e0f-febb-44cc-b04c-2ed6d10d8d4d',
 '47ecbc89-15c2-4e5e-b1fe-6f878653cdbb',
 '6f359e71-3d0f-4704-b44f-f33a540fe7f5',
 'e72459a3-3ffc-452a-b332-ec1c2916c734',
 '2825b799-4753-4789-92fd-092cb6f9dcd4',
 '2935676f-f749-4630-a091-adbbae223fb1',
 '3de3d370-08aa-40fa-a808-c73c2b0e1078',
 'f9445b5f-46bb-4b59-90c9-e84b663ffa42',
 '2ffbc59d-730a-4581-aefc-140b8471dea3',
 'd4b9015e-9272-4acc-aa29-2040ba67a1bd',
 '27c3fc0a-e15b-43c2-8ba7-91627434cc14',
 '15afd220-3887-4fb6-97c4-2fe71d4fb0b1',
 '818f5774-b0be-42cf-b80d-0f8ea8aaa348',
 'ddcf040c-f72b-4824-9f4a-b3c8291934b8',
 'd8865268-093d-4c43-a6b7-64004d5c8173',
 '9db02a8f-6ded-442f-95a5-a9f1ff6fdf1b',
 'e058e42b-3109-413d-b705-61d25ab71d18',
 'f2e941f7-febd-4545-8b5a-e0581e087e3f',
 'fc6acd09-e637-42a0-9eeb-79632ae4f2cc',
 '8efdd6d1-9e59-4f3e-8647-fcab6d51d94a',
 '6713aba9-39f7-4b5d-ad38-15ceb55a467d',
 'e8741582-6e3d-42dc-864c-91f844939b62',
 '3c85b98f-7ee2-4912-9d5b-ac88c7f32015',
 '561f9cef-ea1a-4246-ad03-dd21031ab7b6',
 '77356876-08a6-4fc4-99ed-da625a484065',
 '2ae50cf1-4844-4fc1-8796-c1fb7e3b127c',
 'd05765d2-f0bb-48cf-ab56-c1ed239d1ad4',
 '7023500f-0cf0-4114-8b95-22a279194dd7',
 'c62706df-dfed-4363-a9ee-eb78a5c58ca1',
 'eb7c63c1-6faa-4c41-9ccf-c37cadaef107',
 '5b47ec77-b2db-4fca-9a26-6983eb19bc38',
 '77093466-5102-4347-bba0-110f549e06cf',
 'df61b33e-f40a-4dd7-ae44-ee007ac760fd',
 'f78a2ade-c4bb-4a18-9b5c-dc71292db5da',
 '60f73953-9e3b-4eb0-8172-dd9a73a0b4ca',
 '98b4e587-69f4-40d8-bb92-fa27cf3a7968',
 'bbf3fce7-38da-4d13-93a0-0718d27bb7f7',
 '931ad008-c8c9-4a31-9f45-4f63a05ea5a9',
 '05580261-a18f-43d9-9894-3dea4c9334d1',
 'fc3f8802-7c90-4911-9999-da10b11b0294',
 '8cb0ab10-487b-4d21-9190-c433c5f6fa42',
 '371cf02c-f0a4-49d3-b918-51cdfdfe5d35',
 'ece42f27-861c-4b42-b287-cb885e4335e8',
 '4d46ebb9-3ac2-4e0c-b11f-46683d34f603',
 'b9507a4d-a52d-4053-90e8-676faf0940c4',
 '807f3277-a325-4bdb-a29c-44d3da74e2b2',
 '17235ac2-a232-4039-bdbb-9bd785644e18',
 '7ea20619-0292-40fd-b22c-2563af876771',
 '85f63797-6e1f-42ee-8cd6-709358e1c9d0',
 '8aa73fdc-8a0a-4716-84c1-2c316dfcb350',
 '2f1e854b-96bd-40cb-8a86-d899e209a5d9',
 '7713ca69-c39a-4bc0-9535-ae402a50ef0c',
 '5104ac24-c4d1-4d74-89fd-79883096cf4d',
 '2332c8d8-8bff-4489-a260-5095bbb60123',
 '3d59f773-1f72-4253-9276-209fee67ed1b',
 '5eb9e9f6-c76d-4d05-a79d-e32d809d3bf9',
 'addfe62e-36a2-4386-b689-18b5f4abdaf5',
 'e2c2ee60-7975-4af1-bcfc-8935f082f7cf',
 'c8046cda-7867-496c-b6c2-aa1b341c6c76',
 '2d923c8e-ba15-4155-8d61-c3e3de9bc344',
 '41089f31-500c-43c2-ad71-f265cbca07c5',
 '15cebb2b-4512-4e23-b988-382e8e73656e',
 '0844e285-f082-423c-b1c8-6425c70ce5ac',
 'ecac6a06-ae0c-42be-b575-da7c4ea27b6b',
 '31cecb81-ada2-409e-9b45-3c198d4174db',
 '6e0dbb46-d87d-4845-b0f0-b2d119e17275',
 '39ab77dd-4dd2-4bb0-8b06-dcd95fa3e0a9',
 '5cb5d323-ac28-4b97-bed5-552f1d525c19',
 '025866b6-486e-494e-9337-b9264ad9e20f',
 'f42e34c5-dd4d-4841-bcec-aa443e9c8d17',
 '9426bbc7-ab83-4731-a962-00537133b9df',
 '0d9411d1-5d79-4cc6-a225-38c8f00946a9',
 '103c302e-da3f-494e-a2cd-4dae1eef82a1',
 '7145906a-25cc-4947-9f01-5bf641636859',
 'c223a1ea-eadc-495e-a2e5-083e35e7f671',
 'caef07d1-d804-4ce4-aa80-db6c60cad11f',
 'f6923348-8714-4313-a7c2-488e0f573c5c',
 'b09e29e3-4b10-4bb0-8308-cafacaeb7c2c',
 '4d923cf5-7e46-44aa-ba4b-909ac6c746d5',
 '93360a2e-2c1f-48da-87a2-766564c9818a',
 '3171b18c-e70e-42b6-9722-46f9c113e2ba',
 '3bc6d599-a15f-470d-8688-0dc4703c138b',
 'cbb1fd83-334b-4817-9929-ae162b9cc0d5',
 'a762e7e3-4f46-4e47-9bde-2f49ea75ab7e',
 'fb3fe059-ff3b-4657-afa0-930d5b48a7bd',
 '8858c139-5b3b-4689-a45e-bee9faf30847',
 'db2bed83-cddc-47f9-beee-40989b3f14dc',
 '4815d516-cb55-4f2d-8234-c18addda0c75',
 'ebf50290-298d-4080-be2b-3539c33336cb',
 '2d477e9a-d707-4196-947f-7b6f632f3c70',
 '94da83ee-25be-4ca7-8fe8-ff81eb7abde8',
 '9b16e4c6-76b0-48b7-aa23-84bede4247c8',
 '185244e6-0097-4ccf-8955-867975b61cca',
 'a210a481-3449-44b8-b028-117fd7327ef0',
 '8156b160-6de8-45ee-98d0-d64cb8a3df66',
 '1f316530-4766-4ec2-accb-69a2769dba39',
 '5097dee5-035a-487e-8ec6-36c0ab6b3f99',
 '363e7b0b-b15a-462e-b5f6-c0453dcc409d',
 'd3fba342-8eb3-4ecf-aed3-20239f4a4689',
 'ca87fbe6-fdb7-44dd-8976-22cd0702d4bb',
 '040c8aa3-eeff-43d2-966c-8c7333040042',
 '1233d2f2-a676-49d3-b4ce-8e41006eb3fd',
 '00f50819-6d4f-4116-8e75-fbce32b4038b',
 '97d603b3-417f-434a-ae54-15ea7eb659a5',
 'da7209a2-874b-47d1-833e-1da6ad80dc04',
 '69e93a09-754b-4b26-a929-54b7c9e60711',
 'fb6142e1-9e8a-4c7d-99a2-9b0ef8b753f3',
 'fe368306-d0f7-460b-94a0-acd62a72c66a',
 '9efb9927-2edb-470b-af4e-dcbe22737e16',
 '7bc48590-0a3b-4cff-88ce-d93135a7a794',
 'ac07ea70-a4f4-4607-95e7-6539e95bf910',
 '4807945a-899b-43e2-83d4-f2081240316b',
 '6cc5801d-89a0-4a6e-a6a8-9f7847ee2637',
 'ba355b15-5f43-401f-81c4-a7906e9e265c',
 'eb5a9725-1788-495f-baf0-96fc332e55c9',
 'ba16e807-ee33-4a37-b082-2a1cecbbec3e',
 'afe30f05-d4ba-4a57-890a-1502fef7fb7c',
 'fc72971e-8277-4ed3-b9ec-ed59dccee414',
 '9ad056ec-2795-4881-8747-95c2c6f176aa',
 '04ea050e-de00-4e3b-b93d-ea028253f552',
 '6acb5fb1-937f-4aed-8a77-33ea90499c68',
 '61b316af-af34-430d-b5f4-5d96b9e5aff5',
 'c0a23ebe-7efb-4c14-9f21-af9feee4f8bd',
 '871ba440-c842-44b8-b4de-4850d5624832',
 '63866471-400f-4a59-8787-266caa6d4db5',
 'd460fb50-87f3-4481-9d20-abd8c7f470ec',
 '08446547-317e-4608-8f36-b2e9a4144d75',
 'ce493e93-3d79-4364-9e2f-6c8807fa323e',
 'c9c91e27-b981-4190-8e6a-805db077728b',
 'b1408695-f6ca-4743-823b-1725bb483b20',
 '9178ca21-cdd2-40ba-bc78-efbdb0ca454e',
 'e6f41cca-b8b6-428d-8ab4-613a3c78ef91',
 'fbaeaeb3-2da2-43d6-b267-48ff78f2210a',
 '012ea57c-e019-46aa-af0b-ec8e67f41af0',
 'c7bb097e-6c07-4f2b-ac20-cdf984c49bf1',
 '0ea38693-3676-463d-97a5-849c735a2ad3',
 '43464a01-a106-4b49-86b1-bd9fa6d5ff1a',
 '43a419ae-ef96-45a8-a4ee-c3d8b6954c78',
 'a2983d9f-2a7c-4946-a905-378c01e27417',
 'd8148917-3bc0-4fa0-8280-de2e0472632c',
 '07517b00-b07e-442d-b22e-f0542359f623',
 '3c14e31b-6e78-4652-9343-86697d501663',
 '23c64223-dbf5-499f-a668-03af942fce72',
 '903027ac-2982-4982-b2d9-f7c241e804e8',
 '21b1d4c7-c016-4cd1-a818-678e61e7d625',
 'ab5471b5-d9c7-4617-ae78-d8c94d470c06',
 '6e84d038-bdfb-40aa-b805-369e89e19efa',
 'd5d1c1a3-faad-49d3-9433-aef6c681b06e',
 '1b15012e-7b19-492a-b6fc-64f7b8fe6661',
 'c19e7164-a7a8-41e2-a32b-2c666ff0c2b5',
 'f9178876-d786-4a9e-893c-03b833db38d9',
 '54f65af4-a64a-462a-a776-5c2f9b958a6f',
 'dc472707-0d50-4809-9ea7-1e0ebe398407',
 '90a1c366-0d1b-43ef-84d9-c99f193a8f74',
 '99620aa7-8a2d-4960-a228-73e14129386c',
 '6c76c412-6d3d-44d2-9f34-2a1b372987d4',
 '205fdf0d-5c85-4b94-88ac-306f0b2fb384',
 '073962ac-38f7-4b7e-87d0-08008730088e',
 'cdea2642-ed95-4643-9fe0-86bf8406a9f9',
 'bb2459c6-f681-400c-8b0b-e19fe8ab0f59',
 'f2995b39-7673-4105-ba0d-8f1a1892fed9',
 '772e649b-1a63-4dc2-bb4a-10f1550ecf8f',
 '5ca9a543-299e-4f7d-a895-5e81acfc97e8',
 '6474c98d-09d6-44ec-b811-19b5d9d63160',
 '98162db2-19b5-4e7c-87f7-51064b361939',
 'a89f12f9-9734-45dc-8865-f988fba46fad',
 'ff19a5f9-2271-4420-ba7b-22c83ecd3d87',
 'a71527f2-f655-4c4e-8b7d-8730b0cea098',
 '5727e184-5045-4fad-b9bd-c7873dff063d',
 '81d76e93-01dc-4cc1-87a9-375591832480',
 '61ddbbb6-3ccb-4785-b853-21f72dda2dc8',
 '6f6c6a3f-0427-4524-b1e5-f90e6fab73c0',
 'f4ab81b7-b8fe-4da3-917c-26388220d7f6',
 'a674a4d9-ec4e-4a1b-9dfa-44697167c57f',
 'fbfc18cd-4d79-45b2-b7d8-84aa0102df38',
 'ca460614-0a00-421f-8c48-2a5eeaf05243',
 '3f90bbc2-fd52-44ba-a40f-43aa50dedb05',
 '068a32a0-d4b3-45d1-aad4-3531b9a3fe41',
 '17c0abb6-3f7b-4159-b1df-9a7d3653f6d6',
 'f32b4e56-8e8e-4e6e-93f8-3ab85be7c82d',
 '878bcad3-7830-4175-a807-48427558a943',
 'e4ba9fba-b079-4c26-b6eb-0a87cb064c26',
 'cc7b22d1-d289-4a76-b3f8-3b8d3335b65a',
 '9c387374-6b27-4c67-bdbc-1849df880b68',
 'b49a05bb-2f0f-4918-8ea1-b84a2ccc152f',
 '10249c0e-9137-430a-abc3-df850a63c71c',
 'd9a7e340-9776-48f1-b46f-44b0362d7943',
 '49cd4b97-eaf5-4793-b915-30df15d20011',
 '6673a6bd-e693-4363-ae62-947432fddde2',
 'f5ded079-d29c-45b0-a248-ccfe84de0861',
 'cc759f60-7eae-4278-b6b5-83957527f669',
 '3ccde7a9-9949-4db4-9dea-b8c33b07189e',
 '386d8e77-1db9-4c2a-b1d1-606370233497',
 '15a89b86-c0c2-45d5-ae60-f55b042b416f',
 '24a49ae6-cee7-4b9a-8f47-d172b174050f',
 '95f513e3-d738-4cae-b144-156f29f27cf7',
 '5fd7f5e9-0e5a-4afe-b844-ea1c559495e7',
 '1b38d8e5-bc90-479d-8a97-29f9209d93a8',
 '1f467158-2229-4651-bf92-01f136a90b9d',
 'e0fdcfa5-1b42-4500-bae4-37a7847568c3',
 'e758bc10-8c54-474d-8332-6cbffdef8854',
 'c2d27df9-7589-45cf-af5b-f4a51776d14f',
 '1d51ac4d-1d48-434a-b689-54a714b42649',
 '48b0655c-6414-4b5a-ac83-70f3d8a582e0',
 '8e4d2fce-eeec-4183-93e2-2bdedd5e9a30',
 '2528a907-6c18-4bc8-b721-0f5df8f894e9',
 'd5d01901-06db-4b05-b2f4-fb51487e89db',
 '8ea4b4f7-8e19-4ae9-8cf0-14d409624e8e',
 'af7a9198-464c-4a48-ae99-8da9048c500a',
 '7e673e87-4098-4bb3-891d-c26b2fca761a',
 'ca39ee0c-0656-48df-a921-5b49b02d5e4f',
 '9e206115-cc96-4fde-9f5f-d791afd0fbea',
 '4e396965-f6a2-42c8-8b26-701a16a1d215',
 '75f44a75-ea7d-4e19-9dbf-075470b5965d',
 '61755f6b-1748-4e38-a3df-c4e0d6cee28b',
 '1b7a7037-0540-4ad1-9aa8-a7f530ec68d5',
 '2a6c1ac0-c578-4b65-9da3-b41c606eeefb',
 '7d0768e0-1ea2-4bc1-8cea-a82baec473b8',
 'c56b3cef-25a0-4e8e-98d8-731228095ce3',
 'fe1d669b-5c6a-472d-8971-f6eb4f446dfc',
 '9d484571-c11a-4f50-ad4c-43e415be3034',
 '98159f8f-0997-4531-b430-7e39bc328125',
 '8a012f51-59af-434c-89e6-465ce6267487',
 'ea87cec4-7052-45cb-8fa0-a923630b2b60',
 'c9bc95df-13ab-4c8d-b0bf-9da19bf2194e',
 '4e0c1496-440e-411f-b611-7c6080dd589f',
 '3ec7bec6-f1f3-4d30-a0e2-704060a6c8c9',
 'cd676daa-c39c-4458-8ca1-afddc3493147',
 'f0b995fb-e58d-4263-a880-1c5d619f55b4',
 'db033118-a600-47c2-bca8-aeaf295e806c',
 '645449de-c3f1-43f1-8c65-79fd42052182',
 '8c6686e4-a8d9-4223-aa2b-380b8d15cde9',
 '8ac6a0f9-8c2e-42a9-a9fe-5435d22018a9',
 '5c75243f-0f0b-4f26-aa2e-95f2f453089f',
 'a8b8f2d7-5519-4293-9f33-72bb01b9d59e',
 'acd87781-52c5-43dd-bec5-f5a1b11b39f6',
 '3e68f87b-8834-4504-9133-8f72c4f226d9',
 'dba523f2-1a30-49f0-bd60-0e0660bd7571',
 '2e080abf-b390-468b-be7c-fa518d2a445b',
 'b8b14256-3897-4a2d-b9fd-a3c2a4a8232c',
 '6c18422e-6162-4f0b-a030-02b9004018ae',
 '076aaceb-9f92-4e1a-b95d-d6768f389f76',
 '254a3c5e-a5dc-4028-a9f2-191a78b7f9a3',
 '2ada094a-6f47-4a93-8566-141ca9ffb71f',
 'f979a88c-253a-453b-9726-636fe2d67eff',
 '55498455-6201-4fd0-b595-9c9ea2cddb85',
 '207fb61c-f7d7-4e2d-9072-9ea76859ba84',
 'efa67fe7-b1f6-46b7-ae61-33f1252ff3b0',
 '6bcef8b5-932e-4725-9a5a-c419b49f19cb',
 'cb97a2c8-3c08-404d-98f4-65dfb77613fe',
 '9ab6e44a-fa48-4837-80c1-60613d9f70b6',
 '19fe74ea-46b6-4408-8658-06ef36fa295d',
 '8d15cc4a-9398-497d-b74e-9838f4deb8c6',
 'fba89c71-c48b-41ae-8999-1b6f58624e0e',
 '2bad7a94-68d0-4581-bc06-5f0cde62c362',
 '9dde29a6-3ad1-47b7-821b-73ee508736df',
 '057838bf-c2c0-4d6b-a477-1ee694646746',
 '7b5ab72d-f8e1-4fba-bc5c-0f48204b9c23',
 '2ceb60b6-1dd3-4712-8c61-9ecba9311537',
 '84fe1e9f-132e-4646-8386-c31422a11d66',
 'f4f5cb66-7db0-457c-84b6-46e193d84fe0',
 'ab4d31e0-12fb-40da-b8ff-acc2d453e661',
 'd03b3f93-35b2-45d4-b877-442a73e14b36',
 'efb8d200-159b-4849-9e58-4082a5478185',
 '8f3bcbaf-9a82-4790-9774-50aa1307e9f8',
 '5aa6f21f-198c-4e61-9559-c93f4009e7da',
 '99c67f17-a121-474a-8393-ec973b9f75f6',
 'e7121183-61c5-4388-b51b-f96188e389e8',
 '1e7bb174-9117-4951-be92-8f95186ec6cd',
 '4d18a9b6-33eb-449a-8748-511560564719',
 '1f4c2137-8341-46f6-b173-a9483fc4fe0f',
 'db2de246-1a9d-4ade-971d-7f256bb867b2',
 '9d7c9b58-b1b1-4f12-9c30-1d1a3328ba5b',
 'c5c02e88-b0d7-4315-a00c-4da592e5f262',
 '3821c584-865b-4700-9420-ec351b5083d7',
 'cbd46497-7de9-4891-b4d4-2d8bc76d2eee',
 '5d2029b7-6076-45c1-94c1-1943a1ac2f7f',
 '367708d8-eb1b-4c86-936e-fd00fc15668b',
 '7c0821de-9a7c-444d-af34-0692ca34e8c6',
 '32062546-52b9-43dd-aaf5-b30521175875',
 '918fc7a9-5606-47b4-a608-ac24f598240c',
 'e10714b4-b93c-4c4e-9714-0f114ee24964',
 '3bf7888f-7244-4fef-923d-55ccade47955',
 '5adefc01-fece-4bf7-a3d9-26259d7a3441',
 '6e834d2b-cf58-4b51-874f-82f76210b54b',
 'f620f8ee-069d-4a91-bc12-a3b7ed7f1db3',
 '109806f2-90fe-490e-9061-f73b569579f8',
 'f111d096-b345-48f0-a6b9-6a16fb57e111',
 '9295aa6c-813b-4f89-93ba-c766edf6b1fb',
 '2d819564-96fe-4468-bf30-46482c040161',
 '131055ef-96b4-4905-9a78-c98f07c06c07',
 '9726feb4-3898-4850-b48c-b29a98ba659c',
 '0d1d02b0-47a5-4c9a-83c4-d8212f9e7098',
 '8195deb8-e0f3-4233-b4a4-f057c198cb44',
 'a762f77d-b583-48ff-8f82-56daf8ae3aea',
 'c3ef8aa2-4672-4bf6-9062-b65e8ac56957',
 '03772622-7c24-473e-b899-6457dfd1661a',
 '49fa2b40-97d2-4dc5-863b-d09b70cfe1bb',
 '4c96c78a-daf3-4963-9b76-2e8fb1e35fb7',
 '7e66dc4f-5894-4dca-8e1c-ce018fe4118f',
 'ca4f7635-7f22-4226-b644-0e552084665c',
 '7c67c353-1435-4dd5-964e-c8ca724baeee',
 '4ea86c58-010d-4619-b8ea-1f3fc3b960e7',
 '1f60ca0c-fbc3-42d5-84d8-a2e4c35ffb71',
 'c8b4e261-c0a0-43ee-9a7b-c5404533730d',
 '32c04b80-949e-4e8d-b4e0-06fe94b8486b',
 '5d828ce2-6e55-45e8-bbe4-cfe43d201a3f',
 'eb8f17d9-deed-47f9-a0a5-ab4a24675042',
 'c73cd1f0-5e3c-451d-9fea-0aeeac4f07cf',
 'c5604836-1594-4686-ad74-fa6ba1dc3bb0',
 '0b2894cf-a575-447c-8c5e-242574200605',
 'd66a18f7-ec11-468a-8b57-e18cff37d6b3',
 'b12e483d-62aa-4d62-bb18-aeb2a3ac470e',
 '32cb6a02-71ac-4306-98ce-dffdbcdd0802',
 '3b4e7291-426d-445c-8229-5a914322eb4d',
 '1ba58856-051a-43c0-b13a-65bb3e6a694b',
 'd0c94007-a3ce-4619-a362-e27642ddbb04',
 '3ea738b3-1cd3-4df2-b098-bdabb9118e3e',
 '8c53e1b4-2403-44c2-a964-3ab1fa0477ce',
 '897e9481-e624-4029-803a-b2e190fed4bc',
 '592a990d-bcf1-4027-83a8-168e53ed17f6',
 '5ed78e60-8b5a-4fa6-ac9f-4d9909dd6593',
 '81c5b71c-646b-4b60-9569-d410be94cd8a',
 '8af9526f-9284-4825-8047-c33f7bb110dc',
 'c97bc614-9e7d-4e36-9b8e-c2502bda6b4d',
 '66c9fab7-8c72-44ff-8714-1a680775a81c',
 'd22958fa-be5c-4041-8435-d6b8687b1142',
 'b8a9304f-00b4-42ac-9367-b586271dac2a',
 '56af06e5-48c0-4638-9edb-a69a224f0cfa',
 '48d3b584-8cd8-4be0-8cb9-2bdc7bb6af5c',
 '48b107a7-c747-41f5-8aee-4dc4fdb6c8ea',
 '06549f99-e154-4884-b02b-4d1b917852ae',
 '78d285b3-b3a9-469d-b1e9-271bfac57379',
 '849c68a4-e310-40a2-9602-8c9e20624414',
 'd869ba5a-bd91-4d62-a45a-7932e7f5e570',
 '0a574897-fd18-4386-a288-566579adea30',
 'b908e329-3f85-46e7-aa40-83aaefaf835b',
 '0cd56c66-57ad-49ff-a3b9-585f9473d178',
 'b61ef608-c85e-4309-8bd3-a343b73f7022',
 'a41f8a1a-ed53-4f8a-b4cc-1aab77f86be1',
 '4f9cb5ce-dd21-407c-bd61-cdf903c42793',
 '3dd091b0-d249-4d08-8272-0e6616b4c85c',
 '76ad5283-e841-47ec-a6d6-7a55659909ae',
 '91f453d3-c603-4b3f-9a57-74142bc1260c',
 'ea7a7aa6-fecb-488c-ab40-9bd673d09230',
 '41d8d704-afff-492e-a058-b43f27df3c06',
 '989c0858-6e25-473c-947c-b81b47bf1ccc',
 'ca5a5aee-caea-4201-83fe-d81c0d6a0df8',
 'b164029b-0bf8-43a6-9b29-8d61cf1d067f',
 '8ca59411-0cb0-409c-95ba-dd3b1166c450',
 '4ca1796b-f368-4d73-83a7-d1a1a5730f41',
 '4ab15dfa-b953-489a-a1ba-b453c46dcf57',
 '8fb9a20e-f8dd-435f-be34-81fcfaa905f2',
 'd3e3aebc-999d-493b-88fa-9dce50364639',
 '795fe72b-43aa-4174-a108-eb98ae254383',
 'd2791b31-149b-465e-bfef-74f8136f846f',
 '23f52612-73f2-4a34-9efd-89140c8faace',
 '1f4bf377-1594-429b-bd41-bddcbe016bdd',
 '6d51f32b-a716-4588-adaa-c9ea7fa5b763',
 'd67b22be-6c8b-44f2-a511-da1b3ee470e0',
 '3a67ad3c-b443-4e15-8b60-390220bcf892',
 '3ad07371-a966-423f-abd1-b676a49535ce',
 'be743232-3851-4811-b287-7382105ab69a',
 '6ff9e2c0-ddbc-49ad-a784-a4295db97441',
 '783da801-0a4c-4861-90ad-db629de855b1',
 'b8d92d20-e56c-408d-9e03-fa6226f7b01e',
 'ee656f16-1780-4b8c-a2e8-83e05fa6b676',
 '74c9af6f-81a7-4dd5-b97f-9c2d958dab49',
 'a2168655-9652-43d5-8cd4-b2424df7e914',
 'c297f537-8c6c-4c1b-a21e-e91ae24ce50d',
 '0aa9e575-57c0-44e4-a579-9ffe2062544c',
 'ef8c3270-69cc-4712-9f84-fa21a7dcc835',
 '11df83a6-19ea-4d76-afe8-58d8154f629e',
 '21f33d5a-e375-4ece-b2c1-e9cae67f7b7f',
 '106aa60f-2fc4-4821-b4de-e1571d4972bd',
 '8f70adb0-1493-4e53-b441-d511b0178337',
 'd6fcbd2c-25b0-4445-9203-bc498d02a5af',
 'c92097f2-9c93-455e-98b0-be64259f86c6',
 'e15bc8fd-c878-4d73-84fb-26474421cb5b',
 '89bef542-d56a-403e-be9c-53aaf5d23597',
 'e65e27bc-d3a9-4cdc-9956-93c73520c545',
 '6aa57686-0afa-442e-8a0b-3cc14b6493f3',
 '25d471f9-78ba-433c-b99b-cf8deaeb2eb0',
 'ffe30467-d87e-4c3d-8231-ce2e518fb766',
 'a6f1c7e7-28a1-4496-a17e-7482b538698c',
 '76b94690-e333-4ea6-878d-ec17f21b41b3',
 '539e75be-25d6-453a-8237-89308ffeaff7',
 '85afcc92-15c3-49c8-8dbc-b1e7a6558d31',
 'e7aa671d-1c50-47ea-9699-b02c5228a41a',
 'f16c9be1-9baa-4fad-b3ea-c02c0a0ac5cf',
 '3f4ffb7b-68c4-4a45-88c8-8b20dad80a41',
 '7a3f50db-ecfa-4e94-b7c9-7c68456904a7',
 'ad39fa30-99d3-4b54-9bf2-c2dd181e7b40',
 'c395889f-6598-4bc4-990a-862531ec9cb5',
 'a0fddf4d-b857-46ad-8973-b5e59348e8ae',
 '3144fe31-9ded-4533-aba4-7dae89ce1982',
 'cb60517c-b856-4637-b411-86a3380ae8f0',
 'ca35fe8e-2625-4f99-9216-3696f311d7e2',
 'a49dfe25-c748-4f24-9466-f5ec85dbe367',
 '63ed5e0d-6925-476a-ba95-ff1d1212b245',
 'e22dc4b7-6e79-484b-b8f7-0573eb69944b',
 'd845c9a1-8f91-4ef1-bd4c-b7e7250417bc',
 '4538ed4e-1431-4ef1-99f9-22e059860fe6',
 '22666dad-2a65-4e68-aa17-1b1592432dc9',
 '4b259efd-8513-47c5-ad7c-b0ef7504afc5',
 '0e353a83-c6a7-4bac-b8f7-2e8cb6fe91ec',
 '8997afc5-8386-43dd-b8ed-b378b5dd74a5',
 '710891dc-bcb6-4412-858d-ff80fce5aa28',
 '5fb4ffd3-267b-41a0-b719-0b40b828c395',
 'f083bdcb-b5fa-4a78-8af6-709e8c64bed0',
 'b205030b-f31d-45f4-9319-645063d62ab4',
 '24f89a2c-fbe3-42e4-8cb5-c6258bd7c84c',
 '603dbf44-9403-4fc2-8468-604c8bb55085',
 '7ee1f43a-987e-429f-8149-80db11497637',
 'c0cf9d29-d451-470b-a17e-1fb27af54ca0',
 '03f5d824-d29e-410d-8a89-ed2d817e8b32',
 '135e5aeb-a79c-4363-a8b3-9e67d5438b19',
 '79cc434e-14cd-43c3-bf81-6df3fe799b76',
 '988bca91-3cae-4704-80a1-f7ddca40bbcf',
 'c0c69fa9-88b6-4d89-9e3d-2d459111efae',
 'b67b1db3-aa97-4caa-aa04-f96f7d7c5780',
 '6414370d-57ff-4a2d-8445-be75d54bf4b5',
 '85249818-23a6-4a17-8d26-611f1f5b50e1',
 'bcc59756-8a9a-4b2c-86df-6e87a09fe5e1',
 'f1a8a97a-a1cc-4c1e-bd05-052ececb0c23',
 '11548167-e89b-4890-90d0-34817340cfdb',

In [187]:
results = vector_store.similarity_search(
    "House in New York with 3 bedrooms and not more than 2 bathrooms between 1000000$ and 3000000$",
    k=2
)
for res in results:
    print(f"* {res.page_content} [{res.metadata}]")

* Brokered by COMPASS, House for sale, Price: 14000000$, Beds: 3, Baths: 2.3738608579684373, Size: 23027.0 sqft, Address: 39 Eldridge St, Locality: New York, State: Manhattan, NY 10002, Latitude: 40.7157769, Longitude: -73.99357 [{'beds': 3, 'bath': 2.3738608579684373, 'address': '39 Eldridge St', 'state': 'Manhattan, NY 10002', 'propertysqft': 23027.0, 'price': 14000000, 'latitude': 40.7157769, 'longitude': -73.99357}]
* Brokered by COMPASS, Condo for sale, Price: 3000000$, Beds: 3, Baths: 3.0, Size: 2100.0 sqft, Address: 418 E 59th St # B, Locality: New York, State: Manhattan, NY 10022, Latitude: 40.7590132, Longitude: -73.9612618 [{'beds': 3, 'bath': 3.0, 'address': '418 E 59th St # B', 'state': 'Manhattan, NY 10022', 'propertysqft': 2100.0, 'price': 3000000, 'latitude': 40.7590132, 'longitude': -73.9612618}]

In [188]:
vector_store.save_local("faiss_index_dir")

## LangChain

### Tools

In [189]:
from langchain_core.tools import tool

@tool
def retrieve(query: str, k: int) -> str:
    """Retrieve relevant real estate listings based on the query."""
    results = vector_store.similarity_search(query, k=k)
    if not results:
        return "No relevant listings found."
    
    response = "Here are some relevant listings:\n"
    for i, res in enumerate(results, 1):
        response += (f"{i}. {res.page_content} | "
                     f"Beds: {res.metadata.get('beds')}, "
                     f"Baths: {res.metadata.get('bath')}, "
                     f"Price: {res.metadata.get('price')}$, "
                     f"Address: {res.metadata.get('address')}, "
                     f"State: {res.metadata.get('state')}, "
                     f"Size: {res.metadata.get('propertysqft')} sqft, "
                     f"Latitude: {res.metadata.get('latitude')}, Longitude: {res.metadata.get('longitude')}\n")
    return response

@tool
def average_price(location: str) -> str:
    """Calculate the average price of houses in a given location."""
    results = vector_store.similarity_search(f"houses in {location}", k=20)
    if not results:
        return f"No listings found for location: {location}"
    
    prices = [res.metadata.get('price') for res in results if res.metadata.get('price') is not None]
    if not prices:
        return f"No price data available for listings in {location}"
    
    avg_price = sum(prices) / len(prices)
    return f"The average price of houses in {location} is approximately ${avg_price:,.2f}."


@tool
def final_answer(answer: str, tools_used: list[str]) -> str:
    """Use this tool to provide a final answer to the user.
    The answer should be in natural language as this will be provided
    to the user directly. The tools_used must include a list of tool
    names that were used within the `scratchpad`.
    """
    return {"answer": answer, "tools_used": tools_used}

In [162]:
tools = [retrieve, average_price, final_answer]

# create tool name to function mapping
name2tool = {tool.name: tool.func for tool in tools}

In [163]:
retrieve

StructuredTool(name='retrieve', description='Retrieve relevant real estate listings based on the query.', args_schema=<class 'langchain_core.utils.pydantic.retrieve'>, func=<function retrieve at 0x000001F3FA4B1120>)

In [164]:
print(f"{retrieve.name=}\n{retrieve.description=}")

retrieve.name='retrieve'
retrieve.description='Retrieve relevant real estate listings based on the query.'

In [165]:
retrieve.args_schema.model_json_schema()

{'description': 'Retrieve relevant real estate listings based on the query.',
 'properties': {'query': {'title': 'Query', 'type': 'string'},
  'k': {'title': 'K', 'type': 'integer'}},
 'required': ['query', 'k'],
 'title': 'retrieve',
 'type': 'object'}

### Creating Agent

In [175]:
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder

prompt = ChatPromptTemplate.from_messages([
    ("system", (
        "You're a helpful assistant that will provide information about real estate listings and assist users in finding the right property suggesting listings based on their preferences and requirements."  

"Use tools only if the question requires real estate data such as listings, prices, or property details.  "

"For general knowledge questions or questions unrelated to real estate (for example, about parks, cities, or travel), answer directly without using any tools.  "

"When answering, after using the necessary tools, ALWAYS end with the final_answer tool.  "

"After using a tool, the output will be provided in the 'scratchpad' below. If you have an answer in the scratchpad, you should not use any more tools and instead answer directly to the user."
    )),
    MessagesPlaceholder(variable_name="chat_history"),
    ("human", "{input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
])

In [176]:
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model_name="gpt-4o-mini",
    temperature=0.0,
)

In [177]:
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from langchain_core.runnables.base import RunnableSerializable
from langchain_core.messages import ToolMessage
import json

class CustomAgentExecutor:
    chat_history: list[BaseMessage]

    def __init__(self, max_iterations: int = 3):
        self.chat_history = []
        self.max_iterations = max_iterations
        self.agent: RunnableSerializable = (
            {
                "input": lambda x: x["input"],
                "chat_history": lambda x: x["chat_history"],
                "agent_scratchpad": lambda x: x.get("agent_scratchpad", [])
            }
            | prompt
            | llm.bind_tools(tools, tool_choice="any")  # we're forcing tool use again
        )

    def invoke(self, input: str) -> dict:
        # invoke the agent but we do this iteratively in a loop until
        # reaching a final answer
        count = 0
        agent_scratchpad = []
        while count < self.max_iterations:
            # invoke a step for the agent to generate a tool call
            tool_call = self.agent.invoke({
                "input": input,
                "chat_history": self.chat_history,
                "agent_scratchpad": agent_scratchpad
            })
            # add initial tool call to scratchpad
            agent_scratchpad.append(tool_call)
            # otherwise we execute the tool and add it's output to the agent scratchpad
            tool_name = tool_call.tool_calls[0]["name"]
            tool_args = tool_call.tool_calls[0]["args"]
            tool_call_id = tool_call.tool_calls[0]["id"]
            tool_out = name2tool[tool_name](**tool_args)
            # add the tool output to the agent scratchpad
            if isinstance(tool_out, str):
                # model returned a string instead of dict
                final_answer = tool_out
                tools_used = [tool_name]
            elif isinstance(tool_out, dict) and "answer" in tool_out:
                final_answer = tool_out["answer"]
                tools_used = tool_out.get("tools_used", [])
            else:
                raise ValueError(f"Unexpected tool output type: {type(tool_out)} -> {tool_out}")

            tool_exec = ToolMessage(
                content=f"{tool_out}",
                tool_call_id=tool_call_id
            )
            agent_scratchpad.append(tool_exec)
            # add a print so we can see intermediate steps
            print(f"{count}: {tool_name}({tool_args})")
            count += 1
            # if the tool call is the final answer tool, we stop
            if tool_name == "final_answer":
                break
        # add the final output to the chat history
        final_answer = tool_out["answer"]
        self.chat_history.extend([
            HumanMessage(content=input),
            AIMessage(content=final_answer)
        ])
        # return the final answer in dict form
        return json.dumps(tool_out)

In [178]:
agent_executor = CustomAgentExecutor()

In [180]:
agent_executor.invoke(input="Which are the best houses near parks that I can find in Manhattan?")

0: retrieve({'query': 'houses near parks in Manhattan', 'k': 5})
1: final_answer({'answer': 'Here are some of the best houses near parks in Manhattan:\n\n1. **1211 Park Ave**  \n   - Price: $10,250,000  \n   - Beds: 7  \n   - Baths: 6.0  \n   - Size: 5,200 sqft  \n   - Brokered by: Nest Seekers International  \n\n2. **1070 Park Avenue Ave Units MAIS & 1A**  \n   - Price: $750,000  \n   - Beds: 3  \n   - Baths: 2.0  \n   - Size: 1,600 sqft  \n   - Brokered by: Brown Harris Stevens  \n\n3. **591 Park Ave**  \n   - Price: $10,850,000  \n   - Beds: 4  \n   - Baths: 2.37  \n   - Size: 13,000 sqft  \n   - Brokered by: COMPASS  \n\n4. **740 Park Ave # 4 & 5B**  \n   - Price: $48,000,000  \n   - Beds: 5  \n   - Baths: 2.37  \n   - Size: 2,184 sqft  \n   - Brokered by: Corcoran East Side  \n\n5. **80 Park Avenue Ave Unit 10B**  \n   - Price: $699,900  \n   - Beds: 3  \n   - Baths: 1.0  \n   - Size: 558 sqft  \n   - Brokered by: Brown Harris Stevens  \n\nThese properties are located near various parks, providing great access to green spaces in Manhattan.', 'tools_used': ['functions.retrieve', 'functions.final_answer']})

'{"answer": "Here are some of the best houses near parks in Manhattan:\\n\\n1. **1211 Park Ave**  \\n   - Price: $10,250,000  \\n   - Beds: 7  \\n   - Baths: 6.0  \\n   - Size: 5,200 sqft  \\n   - Brokered by: Nest Seekers International  \\n\\n2. **1070 Park Avenue Ave Units MAIS & 1A**  \\n   - Price: $750,000  \\n   - Beds: 3  \\n   - Baths: 2.0  \\n   - Size: 1,600 sqft  \\n   - Brokered by: Brown Harris Stevens  \\n\\n3. **591 Park Ave**  \\n   - Price: $10,850,000  \\n   - Beds: 4  \\n   - Baths: 2.37  \\n   - Size: 13,000 sqft  \\n   - Brokered by: COMPASS  \\n\\n4. **740 Park Ave # 4 & 5B**  \\n   - Price: $48,000,000  \\n   - Beds: 5  \\n   - Baths: 2.37  \\n   - Size: 2,184 sqft  \\n   - Brokered by: Corcoran East Side  \\n\\n5. **80 Park Avenue Ave Unit 10B**  \\n   - Price: $699,900  \\n   - Beds: 3  \\n   - Baths: 1.0  \\n   - Size: 558 sqft  \\n   - Brokered by: Brown Harris Stevens  \\n\\nThese properties are located near various parks, providing great access to green spaces in Manhattan.", "tools_used": ["functions.retrieve", "functions.final_answer"]}'